
["Distance Scale Settings"]
	#Recommended over 25 000
	scale_distance = 55000.0
	#The scale type can be 'vertical' , 'horizontal' or 'both'
	scale_type = "both"

["Mobs Levels Settings"]
	base_level = 0.0
	scale_factor = 0.1
	max_level = 200.0
	base_level_nether = 10.0
	base_level_end = 25.0
	#Mods after a cartain level get random buffs 
	random_effects = true
	#[1-200]
	random_effects_level = 50.0
	#[1-100]
	random_effects_chance = 10.0
	base_level_territory = 10.0

["Ingame Overlay Settings"]
	display_lvl_name = true

["Random Effects Chances"]
	#[1-10]
	strength_chance = 2.0
	#[1-10]
	speed_chance = 2.0
	#[1-10]
	resistance_chance = 2.0

["Scale Factors"]
	damage_modifier = 5.0
	health_modifier = 5.0
	protection_modifier = 5.0
	speed_modifier = 0.1
	xp_modfier = 5.0

["Advanced Behaviour"]
	leader_radius = 30.0

