Lists = {}

[Options]
	# If you have existing tamed vanilla cats in your world and want to change them to Simply Cats, enable this and restart your minecraft instance.
	replace_tamed_vanilla = false
	# Disables vanilla cats spawning, set to false to allow them to spawn again.
	stop_vanilla_spawns = true
	# Enable or disable the initial join message with a player's cat count.
	join_message = false
	# Disabling this will not allow cats to attack entities in their prey list, essentially a peaceful mode for cats.
	attack_ai = true
	# When a cat's home is set, this is the distance in blocks they are allowed to roam.
	# Default: 400.0
	wander_area_limit = 400.0
	# Sets a limit of cats each player is allowed to have tamed, setting this to 0 will disable the limit.
	tamed_limit = 0
	# This number is used to limit cat breeding; if more than this amount of cats are nearby, automatic breeding will be disabled.
	# Default: 20
	breeding_limit = 20

[Timers]
	# Number of minecraft ticks before a kitten becomes an adult.
	# Default: 168000 (7 full minecraft days)
	kitten_mature_timer = 168000
	# Number of minecraft ticks before a pregnant cat will give birth.
	# Default: 96000 (4 full minecraft days)
	pregnancy_timer = 96000
	# Number of minecraft ticks that a cat will be in heat.
	# Default: 48000 (2 full minecraft days)
	heat_timer = 48000
	# Number of minecraft ticks that a cat will not go into heat.
	# Default: 384000 (16 full minecraft days)
	heat_cooldown = 384000
	# Number of minecraft ticks that a male cat will not try to breed after breeding once already.
	# Default: 6000 (1/4th minecraft day)
	male_cooldown = 6000

